title: Pyre
description : "Revolutionizing fire predictions with AI to make the community safer by at least 20%."
owner_name: Pranav Santhosh
github_username: SanPranav
github_repo: "pyre_frontend" 
baseurl: "/pyre_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/about.md
  - navigation/dashboard.md
  - navigation/earthquakes.md
  - navigation/evac.md
  - navigation/crowd.md
  - navigation/notification.md
  - navigation/historical.md
  - navigation/stats.md
  - navigation/risk.md
  - navigation/search.md
